version: "3"

vars:
  bin_dir: "{{.HOME}}/bin"
  bin_name: "flow-zig"

tasks:
  default:
    desc: List available tasks.
    silent: true
    cmds:
      - task --list

  setup:
    desc: Ensure Zig is available.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v zig >/dev/null 2>&1; then
          echo "Zig toolchain 'zig' not found in PATH."
          echo "Get latest zig using https://github.com/weezy20/zv"
          exit 1
        fi
        zig version >/dev/null
        echo "✔️ you are setup"

  flow:
    desc: Run the Flow Zig CLI (passes CLI args through).
    silent: true
    cmds:
      - |
        set -euo pipefail
        if [ -n "{{.CLI_ARGS}}" ]; then
          zig build flow -- {{.CLI_ARGS}}
        else
          zig build flow
        fi

  dev:
    desc: Alias for task flow.
    silent: true
    cmds:
      - |
        set -euo pipefail
        task flow -- {{.CLI_ARGS}}

  run:
    desc: Alias for task flow.
    silent: true
    cmds:
      - |
        set -euo pipefail
        task flow -- {{.CLI_ARGS}}

  deploy:
    desc: Build the Flow Zig CLI binary and install it to ~/bin/flow-zig.
    silent: true
    cmds:
      - |
        set -euo pipefail
        zig build install
        mkdir -p "{{.bin_dir}}"
        cp "zig-out/bin/flow" "{{.bin_dir}}/{{.bin_name}}"
        chmod 755 "{{.bin_dir}}/{{.bin_name}}"
        echo "Installed CLI to {{.bin_dir}}/{{.bin_name}}"
